language: bash
# secret experimental feature :)
sudo: 9000
env:
  - PHP_VERSION=5.5 MONGO_VERSION=1.6.0 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 MONGO_VERSION=1.5.0 MONGODB_VERSION=2.6
before_script:
  - ./docker/php/buildone.sh
  - IMG_NAME="phpcli${PHP_VERSION}${MONGO_VERSION:+-mongo${MONGO_VERSION}}${XDEBUG_VERSION:+-xdebug${XDEBUG_VERSION}}"
  - docker build -t "${IMG_NAME}" "docker/php/versions/${IMG_NAME}"
  - ls -l ${HOME}/.ssh
  - docker run --rm -v $${PWD} -v ${HOME}/.ssh:/root/.ssh composer/composer install --ignore-platform-reqs

script:
  - docker run --rm -v ${PWD} "${IMG_NAME}" php -r 'print_r(scandir(getcwd()));'

after_script:
  - docker images
  - docker info
