language: bash
# secret experimental feature :)
sudo: 9000 
language: bash
env:
  - PHP_VERSION=5.5 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=2.6
#  - PHP_VERSION=5.5 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=3.0
#  - PHP_VERSION=5.6 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=2.4
#  - PHP_VERSION=5.6 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=2.6
#  - PHP_VERSION=5.6 XDEBUG_VERSION=2.3.2 MONGODB_VERSION=3.0
before_script:
  - ./docker/php/buildone.sh ${PHP_VERSION}

script:
  - exit 0

after_script:
  - docker images
