language: bash

# secret experimental feature :)
sudo: 9000
env:
  - PHP_VERSION=5.5 MONGO_VERSION=1.6.0 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 MONGO_VERSION=1.5.0 MONGODB_VERSION=2.6
before_script:
  - ./docker/php/buildone.sh
  - IMG_DIR=docker/php/versions/phpcli${PHP_VERSION}
  - if [[ ! -z "${MONGO_VERSION+x}" ]]; then IMG_DIR=${IMG_DIR}"-mongo${MONGO_VERSION}"; fi
  - if [[ ! -z "${XDEBUG_VERSION+x}" ]]; then IMG_DIR=${IMG_DIR}"-xdebug${XDEBUG_VERSION}"; fi

script:
  - echo $IMG_DIR
  - docker build -t prova ${IMG_DIR}
  - exit 0

after_script:
  - docker images
