language: bash
# secret experimental feature :)
sudo: 9000 
language: bash
env:
  - PHP_VERSION=5.5 MONGO_VERSION=1.6.0 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 MONGO_VERSION=1.5.0 MONGODB_VERSION=2.6
before_script:
  - ./docker/php/buildone.sh
  - docker build -t img "docker/php/versions/phpcli${PHP_VERSION}*"

script:
  - exit 0

after_script:
  - docker images
