language: bash
# secret experimental feature :)
sudo: 9000 
env:
  - PHP_VERSION=5.5 MONGO_VERSION=1.6.0 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 MONGO_VERSION=1.5.0 MONGODB_VERSION=2.6
before_script:
  - ./docker/php/buildone.sh
  - DEST=phpcli${PHP_VERSION}
  - if [[ -z "${MONGO_VERSION+x}" ]]; then DEST=$DEST SUBST=${SUBST}" s/{{mongo_version}}//g;" else DEST=${DEST}"-mongo${MONGO_VERSION}" SUBST=${SUBST}" s/{{mongo_version}}/-${MONGO_VERSION}/g;" fi
  - if [[ -z "${XDEBUG_VERSION+x}" ]]; then DEST=$DEST SUBST=${SUBST}" s/{{xdebug_version}}//g;" else DEST=${DEST}"-xdebug${XDEBUG_VERSION}" SUBST=${SUBST}" s/{{xdebug_version}}/-${XDEBUG_VERSION}/g;" fi
  - echo $DEST
  - docker build -t img docker/php/versions/${DEST}

script:
  - exit 0

after_script:
  - docker images
