language: bash

# secret experimental feature :)
sudo: 9000
env:
  - PHP_VERSION=5.5 MONGO_VERSION=1.6.0 MONGODB_VERSION=2.4
  - PHP_VERSION=5.5 MONGO_VERSION=1.5.0 MONGODB_VERSION=2.6
before_script:
  - ./docker/php/buildone.sh
  - IMG_DIR="docker/php/version/phpcli${PHP_VERSION}${MONGO_VERSION:+-mongo${MONGO_VERSION}}${XDEBUG_VERSION:+-xdebug${XDEBUG_VERSION}}"

script:
  - docker build -t img ${IMG_DIR}

after_script:
  - docker images
